model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "path to llama-2-7b-chat-hf ckpt"
  prompt_embedding: "path to saved virtual_token ckpt"
  ckpt: "path to checkpoint_stage3.pth"
  lora_r: 64
  lora_alpha: 16


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  pope:
    eval_file_path: "path to test.json"
    img_path: "path to coco_val2014"
    max_new_tokens: 50
    batch_size: 10

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: "output path for evaluation"



  

  

